### ISSUE TITLE
Upcoming Page not working in Safari Browser

### ISSUE THREAD

**Issue by Ashrockzzz2003** [Abhinav-ark/timetable_csea#11]
## Assignments not working in Safari Browser

- The reason for this is unnecessary `module` imports of `assignments.json`

### Solution

- In `assignments.json`, the data can be assigned to a `variable`, which can be accessed in `upcoming.html`, which simplifies and extends the support of the website to Safari users.

**Comment by Abhinav-ark** [comment]
Appreciate your advice Ashwin, but when i tried, i found that .json files don't allow you to declare variables inside them. Do you suggest i create a constant in a .js file and access it in upcoming.html ?

**Comment by Ashrockzzz2003** [comment]
Yes. That'll work!

**Comment by Abhinav-ark** [comment]
Thanks for your support Ashwin 🙌
